services:
  mongodb:
    image: mongo:7
    container_name: psicometric-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: psicometric
    volumes:
      - psicometric_mongo_data:/data/db

volumes:
  psicometric_mongo_data:
